### ISSUE TITLE
Git Lernen Samuel

### ISSUE THREAD

**Issue by jasperspahl** [ballz-gg/maxtemp#22]
# How to git

**Comment by SamuelSock** [comment]
Was ist ein Commit?
Ein Commit ist eine Zusammenfassung von Änderungen an Dateien die eine Aufgabe erledigen.

Was bedeutet staging?
Eine modifizierte Datei wurde markiert, dass sie in den nächsten Commit snapshot kommt.

Mit welchem Befehlt kann man einen Git Commit erstellen?
git commit

Was ist ein Branch?
Ein Branch ist eine Version des Projektes welcher mit anderen Branches gemergt werden kann.

Was ist ein Pull request?
Alle Commits die auf dem Server sind werden heruntergeladen und gemerged.
